# Generated by Django 4.2.1 on 2023-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_extras_pages_extra_split_faces'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
