# Generated by Django 4.2.1 on 2023-05-22 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_pages_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.definition'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='documents_required',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.documentsrequired'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='eligibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.eligibility'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.faq'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='how_to_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.howtoregister'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title_description',
            field=models.TextField(blank=True, help_text='use | for next line', max_length=255, null=True),
        ),
    ]
