# Generated by Django 4.2.1 on 2023-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_pages_title_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="meta_keywords",
            field=models.TextField(
                blank=True, help_text="use comma( , ) for separation", null=True
            ),
        ),
        migrations.AddField(
            model_name="pages",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="if leave it will take from title ",
                max_length=255,
                null=True,
            ),
        ),
    ]
