# Generated by Django 4.2.1 on 2023-06-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_contact_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workhistory",
            name="counts_number",
            field=models.TextField(help_text="use | for next line"),
        ),
    ]
