# Generated by Django 4.2.1 on 2023-06-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_workhistory_counts_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhistory",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="workshostory"),
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="work_history",
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="counts_number",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="counts_title",
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name="homepage",
            name="work_history",
            field=models.ManyToManyField(to="home.workhistory"),
        ),
    ]
